services:
  postgres:
    image: postgres:18
    container_name: talent_hunt_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: talent_hunt
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
